
---

# Hibernate Configuration
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts_db
    username: postgres
    password: password
  sql:
    init:
      schema-locations: classpath:db-scripts/schema.sql
      mode: always
      data-locations: classpath:db-scripts/data.sql
---

spring:
  config:
    activate:
      on-profile: prod