version: '3.1'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: switcheroos_db
    ports:
      - "5432:5432"